### PR TITLE
Add archive functionality

### PR DESCRIPTION
**Pull request by braegelno5**
- there exists a new Views/Blog/Posted.cshtml view linked by the word Posted on every blog post
- on the new view we are able to simple search in all published posts for not admin users, jump to an anchor for all posts by there category, 
- ore we are able to switch the view to a calendar control to iterate forwards and backwards throw all posts, here we are able to jump to posts for a year, month and day

### CODE REVIEW

**Comment by madskristensen** [comment]
Thanks for the PR.

That's a big change and a big PR with no discussion first. Did you implement a tag cloud for this as well?

**Comment by braegelno5** [comment]
yes it's not a small one, are you able to check the pr from my own branch: https://github.com/braegelno5/Miniblog.Core/tree/add_archive_functionality ?
and yes there is also the tag cloud implemented, but without color - only font sized

**Comment by braegelno5** [comment]
Have now added on azurewebsites.net a test host from my named branch with the same functionality for this PR: https://miniblogcore2018archive.azurewebsites.net/

**Comment by braegelno5** [comment]
A other suggestion would be: adding this functionality to the main page and show them on the left side on desctop browsers, on mobile ui add a menu button to get the controls?

**Comment by braegelno5** [comment]
for refactoring, closing

**Pull request closed without merging**
