### PR TITLE
Split image handling into its own service and created an azureblobfileservice

### PR DESCRIPTION
**Pull request by CeriQ**
Also added configuration and configuration controlled startup for azureblobfileservice.

### CODE REVIEW

**Comment by madskristensen** [comment]
I appreciate the PR, but a Azure dependency is not something I'm willing to add. Sorry

**Comment by CeriQ** [comment]
You decide of course, but there are no new external dependencies outside of the .net core libs. It's also disabled by default.

Either way, it was a fun exercise to get started with core.

**Comment by madskristensen** [comment]
But you have this which isn't part of the core lib, right? `using Microsoft.WindowsAzure.Storage.Blob;`

**Comment by CeriQ** [comment]
It's already in there via Microsoft.AspNetCore.All, see the attached search in solution explorer.
microsoft windowsazure storage

**Comment by CeriQ** [comment]
I took it upon myself to write this feature. There will be no hard feelings if you decide that it's not a good fit for the project.

**Comment by thomaspleasance** [comment]
I like the idea of IFileService this would allow people to use other storage systems.

**Comment by tbasallo** [comment]
I hadn't even seen this PR. I was thinking through the same thing https://github.com/madskristensen/Miniblog.Core/issues/51

**Comment by CeriQ** [comment]
I'm guessing this won't be merged. =(

**Comment by CeriQ** [comment]
Since nothing appears to be happening, I'm closing this PR to remove it from the waiting list.

**Pull request closed without merging**
